/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package typing.tutor;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author Zarar bhai
 */
public class Lt4 extends javax.swing.JFrame {
    static String lesson1="eruiuilajflajlflalfdlaljsflka;aklsl;jalsal;lajajeruiiueiurkdkaslfjakldklaklfa;lsllslakdsasuiuiresera";
     private java.util.List<JLabel> label;
    //public String str="abcdef";
    int currentchar;
    int z=0;
    static int error=0;
    static int currentChar=0;
    static String str=null;
    /**
     * Creates new form lesson2
     */
    static int seconds=0;
    static int minutes=0;
    static int hours=0;
    static int miliseconds=0;
    
    static boolean state=true;
    static boolean s=false;
    /**
     * Creates new form Lt4
     */
    public Lt4() {
        initComponents();
        label = new ArrayList<JLabel>();
        label.add(l1);
        label.add(l2);
        label.add(l3);
        label.add(l4);
        label.add(l5);
        label.add(l6);
        label.add(l7);
        label.add(l8);
        label.add(l9);
        label.add(l10);
        label.add(l11);
        label.add(l12);
        label.add(l13);
        label.add(l14);
        label.add(l15);
        label.add(l16);
        label.add(l17);
        label.add(l18);
        label.add(l19);
        label.add(l20);
        label.add(l21);
        label.add(l22);
        label.add(l23);
        label.add(l24);
        label.add(l25);
        label.add(l26);
        label.add(l27);
        label.add(l28);
        label.add(l29);
        label.add(l30);
        label.add(l31);
        label.add(l32);
        label.add(l33);
        label.add(l34);
        label.add(l35);
        label.add(l36);
        label.add(l37);
        label.add(l38);
        label.add(l39);
        label.add(l40);
        label.add(l41);
        label.add(l42);
        label.add(l43);
        label.add(l44);
        label.add(l45);
        label.add(l46);
        label.add(l47);
        label.add(l48);
        label.add(l49);
        label.add(l50);
        label.add(l51);
        label.add(l52);
        label.add(l53);
        label.add(l54);
        label.add(l55);
        label.add(l56);
        label.add(l57);
        label.add(l58);
        label.add(l59);
        label.add(l60);
        label.add(l61);
        label.add(l62);
        label.add(l63);
        label.add(l64);
        label.add(l65);
        label.add(l66);
        label.add(l67);
        label.add(l68);
        label.add(l69);
        label.add(l70);
        label.add(l71);
        label.add(l72);
        label.add(l73);
        label.add(l74);
        label.add(l75);
        label.add(l76);
        label.add(l77);
        label.add(l78);
        label.add(l79);
        label.add(l80);
        label.add(l81);
        label.add(l82);
        label.add(l83);
        label.add(l84);
        label.add(l85);
        label.add(l86);
        label.add(l87);
        label.add(l88);
        label.add(l89);
        label.add(l90);
        label.add(l91);
        label.add(l92);
        label.add(l93);
        label.add(l94);
        label.add(l95);
        label.add(l96);
        label.add(l97);
        label.add(l98);
        label.add(l99);
        label.add(l100);
        
        //l1.setText(Character.toString(str.charAt(0)));
        while(z<100){
            label.get(z).setText(Character.toString(lesson1.charAt(z)));
            z++;
        }
        //label.get(currentchar).setBorder(BorderFactory.createLineBorder(Color.BLACK));
        
        min.setEditable(false);
        sec.disable();
        min.disable();
        //hour.disable();
        mili.disable();
        //hour.setEditable(false);
        sec.setEditable(false);
        mili.setEditable(false);
        jTextField1.setEditable(true);
        jTextField1.enable(true);
        jButton1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        min = new javax.swing.JTextField();
        sec = new javax.swing.JTextField();
        mili = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        l14 = new javax.swing.JLabel();
        l15 = new javax.swing.JLabel();
        l16 = new javax.swing.JLabel();
        l17 = new javax.swing.JLabel();
        l18 = new javax.swing.JLabel();
        l19 = new javax.swing.JLabel();
        l20 = new javax.swing.JLabel();
        l21 = new javax.swing.JLabel();
        l22 = new javax.swing.JLabel();
        l23 = new javax.swing.JLabel();
        l24 = new javax.swing.JLabel();
        l25 = new javax.swing.JLabel();
        l26 = new javax.swing.JLabel();
        l27 = new javax.swing.JLabel();
        l28 = new javax.swing.JLabel();
        l29 = new javax.swing.JLabel();
        l30 = new javax.swing.JLabel();
        l31 = new javax.swing.JLabel();
        l32 = new javax.swing.JLabel();
        l33 = new javax.swing.JLabel();
        l34 = new javax.swing.JLabel();
        l35 = new javax.swing.JLabel();
        l36 = new javax.swing.JLabel();
        l37 = new javax.swing.JLabel();
        l38 = new javax.swing.JLabel();
        l39 = new javax.swing.JLabel();
        l40 = new javax.swing.JLabel();
        l41 = new javax.swing.JLabel();
        l42 = new javax.swing.JLabel();
        l43 = new javax.swing.JLabel();
        l44 = new javax.swing.JLabel();
        l45 = new javax.swing.JLabel();
        l46 = new javax.swing.JLabel();
        l47 = new javax.swing.JLabel();
        l48 = new javax.swing.JLabel();
        l49 = new javax.swing.JLabel();
        l50 = new javax.swing.JLabel();
        l51 = new javax.swing.JLabel();
        l52 = new javax.swing.JLabel();
        l53 = new javax.swing.JLabel();
        l54 = new javax.swing.JLabel();
        l55 = new javax.swing.JLabel();
        l56 = new javax.swing.JLabel();
        l57 = new javax.swing.JLabel();
        l58 = new javax.swing.JLabel();
        l59 = new javax.swing.JLabel();
        l60 = new javax.swing.JLabel();
        l61 = new javax.swing.JLabel();
        l62 = new javax.swing.JLabel();
        l63 = new javax.swing.JLabel();
        l64 = new javax.swing.JLabel();
        l65 = new javax.swing.JLabel();
        l66 = new javax.swing.JLabel();
        l67 = new javax.swing.JLabel();
        l68 = new javax.swing.JLabel();
        l69 = new javax.swing.JLabel();
        l70 = new javax.swing.JLabel();
        l71 = new javax.swing.JLabel();
        l72 = new javax.swing.JLabel();
        l73 = new javax.swing.JLabel();
        l74 = new javax.swing.JLabel();
        l75 = new javax.swing.JLabel();
        l76 = new javax.swing.JLabel();
        l77 = new javax.swing.JLabel();
        l78 = new javax.swing.JLabel();
        l79 = new javax.swing.JLabel();
        l80 = new javax.swing.JLabel();
        l81 = new javax.swing.JLabel();
        l82 = new javax.swing.JLabel();
        l83 = new javax.swing.JLabel();
        l84 = new javax.swing.JLabel();
        l85 = new javax.swing.JLabel();
        l86 = new javax.swing.JLabel();
        l87 = new javax.swing.JLabel();
        l88 = new javax.swing.JLabel();
        l89 = new javax.swing.JLabel();
        l90 = new javax.swing.JLabel();
        l91 = new javax.swing.JLabel();
        l92 = new javax.swing.JLabel();
        l93 = new javax.swing.JLabel();
        l94 = new javax.swing.JLabel();
        l95 = new javax.swing.JLabel();
        l96 = new javax.swing.JLabel();
        l97 = new javax.swing.JLabel();
        l98 = new javax.swing.JLabel();
        l99 = new javax.swing.JLabel();
        l100 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Test 4");

        min.setBackground(new java.awt.Color(0, 51, 51));
        min.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        min.setForeground(new java.awt.Color(102, 153, 255));
        min.setBorder(null);

        sec.setBackground(new java.awt.Color(0, 51, 51));
        sec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sec.setForeground(new java.awt.Color(102, 153, 255));
        sec.setBorder(null);

        mili.setBackground(new java.awt.Color(0, 51, 51));
        mili.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mili.setForeground(new java.awt.Color(102, 153, 255));
        mili.setBorder(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        l1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(153, 153, 153));
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l2.setForeground(new java.awt.Color(153, 153, 153));
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l3.setForeground(new java.awt.Color(153, 153, 153));
        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l4.setForeground(new java.awt.Color(153, 153, 153));
        l4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l5.setForeground(new java.awt.Color(153, 153, 153));
        l5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l6.setForeground(new java.awt.Color(153, 153, 153));
        l6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l7.setForeground(new java.awt.Color(153, 153, 153));
        l7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l8.setForeground(new java.awt.Color(153, 153, 153));
        l8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l9.setForeground(new java.awt.Color(153, 153, 153));
        l9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l10.setForeground(new java.awt.Color(153, 153, 153));
        l10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l11.setForeground(new java.awt.Color(153, 153, 153));
        l11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l12.setForeground(new java.awt.Color(153, 153, 153));
        l12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l13.setForeground(new java.awt.Color(153, 153, 153));
        l13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l14.setForeground(new java.awt.Color(153, 153, 153));
        l14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l15.setForeground(new java.awt.Color(153, 153, 153));
        l15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l16.setForeground(new java.awt.Color(153, 153, 153));
        l16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l17.setForeground(new java.awt.Color(153, 153, 153));
        l17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l18.setForeground(new java.awt.Color(153, 153, 153));
        l18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l19.setForeground(new java.awt.Color(153, 153, 153));
        l19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l20.setForeground(new java.awt.Color(153, 153, 153));
        l20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l21.setForeground(new java.awt.Color(153, 153, 153));
        l21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l22.setForeground(new java.awt.Color(153, 153, 153));
        l22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l23.setForeground(new java.awt.Color(153, 153, 153));
        l23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l24.setForeground(new java.awt.Color(153, 153, 153));
        l24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l25.setForeground(new java.awt.Color(153, 153, 153));
        l25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l26.setForeground(new java.awt.Color(153, 153, 153));
        l26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l27.setForeground(new java.awt.Color(153, 153, 153));
        l27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l28.setForeground(new java.awt.Color(153, 153, 153));
        l28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l29.setForeground(new java.awt.Color(153, 153, 153));
        l29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l30.setForeground(new java.awt.Color(153, 153, 153));
        l30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l31.setForeground(new java.awt.Color(153, 153, 153));
        l31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l32.setForeground(new java.awt.Color(153, 153, 153));
        l32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l33.setForeground(new java.awt.Color(153, 153, 153));
        l33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l34.setForeground(new java.awt.Color(153, 153, 153));
        l34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l35.setForeground(new java.awt.Color(153, 153, 153));
        l35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l36.setForeground(new java.awt.Color(153, 153, 153));
        l36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l37.setForeground(new java.awt.Color(153, 153, 153));
        l37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l38.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l38.setForeground(new java.awt.Color(153, 153, 153));
        l38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l39.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l39.setForeground(new java.awt.Color(153, 153, 153));
        l39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l40.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l40.setForeground(new java.awt.Color(153, 153, 153));
        l40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l41.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l41.setForeground(new java.awt.Color(153, 153, 153));
        l41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l42.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l42.setForeground(new java.awt.Color(153, 153, 153));
        l42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l43.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l43.setForeground(new java.awt.Color(153, 153, 153));
        l43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l44.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l44.setForeground(new java.awt.Color(153, 153, 153));
        l44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l45.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l45.setForeground(new java.awt.Color(153, 153, 153));
        l45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l46.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l46.setForeground(new java.awt.Color(153, 153, 153));
        l46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l47.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l47.setForeground(new java.awt.Color(153, 153, 153));
        l47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l48.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l48.setForeground(new java.awt.Color(153, 153, 153));
        l48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l49.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l49.setForeground(new java.awt.Color(153, 153, 153));
        l49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l50.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l50.setForeground(new java.awt.Color(153, 153, 153));
        l50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l51.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l51.setForeground(new java.awt.Color(153, 153, 153));
        l51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l52.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l52.setForeground(new java.awt.Color(153, 153, 153));
        l52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l53.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l53.setForeground(new java.awt.Color(153, 153, 153));
        l53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l54.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l54.setForeground(new java.awt.Color(153, 153, 153));
        l54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l55.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l55.setForeground(new java.awt.Color(153, 153, 153));
        l55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l56.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l56.setForeground(new java.awt.Color(153, 153, 153));
        l56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l57.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l57.setForeground(new java.awt.Color(153, 153, 153));
        l57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l58.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l58.setForeground(new java.awt.Color(153, 153, 153));
        l58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l59.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l59.setForeground(new java.awt.Color(153, 153, 153));
        l59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l60.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l60.setForeground(new java.awt.Color(153, 153, 153));
        l60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l61.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l61.setForeground(new java.awt.Color(153, 153, 153));
        l61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l62.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l62.setForeground(new java.awt.Color(153, 153, 153));
        l62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l63.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l63.setForeground(new java.awt.Color(153, 153, 153));
        l63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l64.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l64.setForeground(new java.awt.Color(153, 153, 153));
        l64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l65.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l65.setForeground(new java.awt.Color(153, 153, 153));
        l65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l66.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l66.setForeground(new java.awt.Color(153, 153, 153));
        l66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l67.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l67.setForeground(new java.awt.Color(153, 153, 153));
        l67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l68.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l68.setForeground(new java.awt.Color(153, 153, 153));
        l68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l69.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l69.setForeground(new java.awt.Color(153, 153, 153));
        l69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l70.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l70.setForeground(new java.awt.Color(153, 153, 153));
        l70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l71.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l71.setForeground(new java.awt.Color(153, 153, 153));
        l71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l72.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l72.setForeground(new java.awt.Color(153, 153, 153));
        l72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l73.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l73.setForeground(new java.awt.Color(153, 153, 153));
        l73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l74.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l74.setForeground(new java.awt.Color(153, 153, 153));
        l74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l75.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l75.setForeground(new java.awt.Color(153, 153, 153));
        l75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l76.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l76.setForeground(new java.awt.Color(153, 153, 153));
        l76.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l77.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l77.setForeground(new java.awt.Color(153, 153, 153));
        l77.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l78.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l78.setForeground(new java.awt.Color(153, 153, 153));
        l78.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l79.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l79.setForeground(new java.awt.Color(153, 153, 153));
        l79.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l80.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l80.setForeground(new java.awt.Color(153, 153, 153));
        l80.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l81.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l81.setForeground(new java.awt.Color(153, 153, 153));
        l81.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l82.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l82.setForeground(new java.awt.Color(153, 153, 153));
        l82.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l83.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l83.setForeground(new java.awt.Color(153, 153, 153));
        l83.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l84.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l84.setForeground(new java.awt.Color(153, 153, 153));
        l84.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l85.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l85.setForeground(new java.awt.Color(153, 153, 153));
        l85.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l86.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l86.setForeground(new java.awt.Color(153, 153, 153));
        l86.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l87.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l87.setForeground(new java.awt.Color(153, 153, 153));
        l87.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l88.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l88.setForeground(new java.awt.Color(153, 153, 153));
        l88.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l89.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l89.setForeground(new java.awt.Color(153, 153, 153));
        l89.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l90.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l90.setForeground(new java.awt.Color(153, 153, 153));
        l90.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l91.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l91.setForeground(new java.awt.Color(153, 153, 153));
        l91.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l92.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l92.setForeground(new java.awt.Color(153, 153, 153));
        l92.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l93.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l93.setForeground(new java.awt.Color(153, 153, 153));
        l93.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l94.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l94.setForeground(new java.awt.Color(153, 153, 153));
        l94.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l95.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l95.setForeground(new java.awt.Color(153, 153, 153));
        l95.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l96.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l96.setForeground(new java.awt.Color(153, 153, 153));
        l96.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l97.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l97.setForeground(new java.awt.Color(153, 153, 153));
        l97.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l98.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l98.setForeground(new java.awt.Color(153, 153, 153));
        l98.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l99.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l99.setForeground(new java.awt.Color(153, 153, 153));
        l99.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l100.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l100.setForeground(new java.awt.Color(153, 153, 153));
        l100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(l16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l28, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l29, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l30, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(l31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l32, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l34, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l35, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l36, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l37, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l38, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l39, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l40, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l41, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l42, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l43, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l44, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l45, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(l46, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l47, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l48, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l49, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l50, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l51, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l52, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l53, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l54, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l55, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l56, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l57, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l58, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l59, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l60, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(l61, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l62, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l63, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l64, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l65, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l66, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l67, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l68, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l69, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l70, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l71, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l72, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l73, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l74, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l75, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(l76, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(l77, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(l78, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(l92, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(l91, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(l93, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(l94, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(l95, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(l96, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(l97, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(l98, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(l99, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(l100, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(l79, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(l80, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(l81, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(l82, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(l83, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(l84, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(l85, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(l86, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(l87, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(l88, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(l89, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(l90, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l18, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l19, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l20, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l21, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l22, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l23, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l24, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l25, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l26, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l27, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l28, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l29, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l30, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l31, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l32, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l33, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l34, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l35, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l36, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l37, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l38, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l39, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l40, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l41, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l42, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l43, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l44, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l45, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l46, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(l47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l58, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l59, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l60, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l61, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(l62, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l63, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l64, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l65, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l67, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l68, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l69, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l71, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l72, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l73, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l74, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l75, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(l81, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addComponent(l80, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l79, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l78, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l77, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l82, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(l76, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(l83, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l84, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l85, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l86, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l87, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l88, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l89, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l90, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l91, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l92, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l93, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l94, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l95, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l96, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l97, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l98, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l99, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l100, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTextField1.setBackground(new java.awt.Color(0, 51, 51));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(null);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sec, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mili, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sec, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mili, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if(currentchar==0){
            state=true;
            min.setEnabled(true);
            sec.setEnabled(true);
            //hour.setEnabled(true);
            mili.setEnabled(true);
            jButton1.setEnabled(true);
            time();
            
        }
        if(evt.getKeyChar()==lesson1.charAt(currentchar)){
            label.get(currentchar).setForeground(Color.BLACK);
            //label.get(currentchar).setBorder(null);
            currentchar++;
            if(currentchar>50){
                jTextField1.setEditable(false);
            }
        }
        else{
            label.get(currentchar).setForeground(Color.RED);
            //label.get(currentchar).setBorder(null);
            currentchar++;
            error++;
            if(currentchar>50){
                jTextField1.setEditable(false);
            }
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        if(currentchar>99){
            state=false;
            jTextField1.setEditable(false);
            results1();
            this.dispose();
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menum m= new Menum();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void results1(){
         int e1=0;
         float s=seconds;
         float t=minutes;
         float tt=t+(s/60);
         System.out.println("the total errors are "+error);
         System.out.println("the total time are "+tt);
         float wpa=100/tt;
         float e2=100-error;
         System.out.println("the total errors are "+error);
         System.out.println("the total time are "+tt);
         System.out.println("the total wpa "+wpa);
         testresult r=new testresult(4,wpa,error,e2,e2);
         
         r.setVisible(true);
         
         
         
         
         
         
     }
    
    public void time(){
        state=true;
        Thread t=new Thread()
        {
            public void run()
            {
                for(;;)
                {
                    if(state==true)
                    {
                        try
                        {
                            sleep(1);
                            miliseconds++;
                            if(miliseconds>1000)
                            {
                                seconds++;
                                miliseconds=0;
                            }
                            if(seconds>59){
                                seconds=0;
                                minutes++;
                            }
                            if(minutes>59)
                            {
                                seconds=0;
                                hours++;
                            }
                            mili.setText(""+miliseconds);
                            //hour.setText(""+hours);
                            min.setText(":"+minutes);
                            sec.setText(":"+seconds);

                        }
                        catch(Exception e)
                        {

                        }
                    }
                    else
                    {
                        break;
                    }
                }

            }
        };
        t.start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lt4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lt4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lt4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lt4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lt4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l100;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l14;
    private javax.swing.JLabel l15;
    private javax.swing.JLabel l16;
    private javax.swing.JLabel l17;
    private javax.swing.JLabel l18;
    private javax.swing.JLabel l19;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l20;
    private javax.swing.JLabel l21;
    private javax.swing.JLabel l22;
    private javax.swing.JLabel l23;
    private javax.swing.JLabel l24;
    private javax.swing.JLabel l25;
    private javax.swing.JLabel l26;
    private javax.swing.JLabel l27;
    private javax.swing.JLabel l28;
    private javax.swing.JLabel l29;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l30;
    private javax.swing.JLabel l31;
    private javax.swing.JLabel l32;
    private javax.swing.JLabel l33;
    private javax.swing.JLabel l34;
    private javax.swing.JLabel l35;
    private javax.swing.JLabel l36;
    private javax.swing.JLabel l37;
    private javax.swing.JLabel l38;
    private javax.swing.JLabel l39;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l40;
    private javax.swing.JLabel l41;
    private javax.swing.JLabel l42;
    private javax.swing.JLabel l43;
    private javax.swing.JLabel l44;
    private javax.swing.JLabel l45;
    private javax.swing.JLabel l46;
    private javax.swing.JLabel l47;
    private javax.swing.JLabel l48;
    private javax.swing.JLabel l49;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l50;
    private javax.swing.JLabel l51;
    private javax.swing.JLabel l52;
    private javax.swing.JLabel l53;
    private javax.swing.JLabel l54;
    private javax.swing.JLabel l55;
    private javax.swing.JLabel l56;
    private javax.swing.JLabel l57;
    private javax.swing.JLabel l58;
    private javax.swing.JLabel l59;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l60;
    private javax.swing.JLabel l61;
    private javax.swing.JLabel l62;
    private javax.swing.JLabel l63;
    private javax.swing.JLabel l64;
    private javax.swing.JLabel l65;
    private javax.swing.JLabel l66;
    private javax.swing.JLabel l67;
    private javax.swing.JLabel l68;
    private javax.swing.JLabel l69;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l70;
    private javax.swing.JLabel l71;
    private javax.swing.JLabel l72;
    private javax.swing.JLabel l73;
    private javax.swing.JLabel l74;
    private javax.swing.JLabel l75;
    private javax.swing.JLabel l76;
    private javax.swing.JLabel l77;
    private javax.swing.JLabel l78;
    private javax.swing.JLabel l79;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l80;
    private javax.swing.JLabel l81;
    private javax.swing.JLabel l82;
    private javax.swing.JLabel l83;
    private javax.swing.JLabel l84;
    private javax.swing.JLabel l85;
    private javax.swing.JLabel l86;
    private javax.swing.JLabel l87;
    private javax.swing.JLabel l88;
    private javax.swing.JLabel l89;
    private javax.swing.JLabel l9;
    private javax.swing.JLabel l90;
    private javax.swing.JLabel l91;
    private javax.swing.JLabel l92;
    private javax.swing.JLabel l93;
    private javax.swing.JLabel l94;
    private javax.swing.JLabel l95;
    private javax.swing.JLabel l96;
    private javax.swing.JLabel l97;
    private javax.swing.JLabel l98;
    private javax.swing.JLabel l99;
    private javax.swing.JTextField mili;
    private javax.swing.JTextField min;
    private javax.swing.JTextField sec;
    // End of variables declaration//GEN-END:variables
}
